apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kustomize-controller
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::290913681714:policy/kustomization-controller-devops-83-dev"
target:
    kind: ServiceAccount
    name: kustomize-controller