apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./secrets
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
      provider: sops