creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    kms: arn:aws:kms:ap-southeast-1:290913681714:key/e7650bc1-899e-43af-9e3d-f89a04668f14
  - path_regex: .*.env
    kms: arn:aws:kms:ap-southeast-1:290913681714:key/e7650bc1-899e-43af-9e3d-f89a04668f14
